USE [master]
GO
/****** Object:  Database [StockBridge]    Script Date: 8/20/2020 7:30:09 PM ******/
CREATE DATABASE [StockBridge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Omobono', FILENAME = N'/Users/Shared/stockbridge.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Omobono_log', FILENAME = N'/Users/Shared/stockbridge_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [StockBridge] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockBridge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [StockBridge] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [StockBridge] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [StockBridge] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [StockBridge] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [StockBridge] SET ARITHABORT OFF 
GO
ALTER DATABASE [StockBridge] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [StockBridge] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [StockBridge] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [StockBridge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [StockBridge] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [StockBridge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [StockBridge] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [StockBridge] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [StockBridge] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [StockBridge] SET  DISABLE_BROKER 
GO
ALTER DATABASE [StockBridge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [StockBridge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [StockBridge] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [StockBridge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [StockBridge] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [StockBridge] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [StockBridge] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [StockBridge] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [StockBridge] SET  MULTI_USER 
GO
ALTER DATABASE [StockBridge] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [StockBridge] SET DB_CHAINING OFF 
GO
ALTER DATABASE [StockBridge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [StockBridge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [StockBridge] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [StockBridge] SET QUERY_STORE = OFF
GO
USE [StockBridge]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [StockBridge]
GO
/****** Object:  Schema [Employee]    Script Date: 8/20/2020 7:30:09 PM ******/
CREATE SCHEMA [Employee]
GO
/****** Object:  Table [Employee].[Employee]    Script Date: 8/20/2020 7:30:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Employee].[Employee](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[UserName] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Password] [binary](64) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[StartDate] [datetime] NULL,
	[RoleID] [int] NOT NULL,
	[UpdatedDate]  AS (getdate()),
	[AvailableVacationHours] [decimal](2, 0) NULL,
	[BaseRate] [money] NOT NULL,
 CONSTRAINT [PK_Employee.Employee] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [Unique_Employee] UNIQUE NONCLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Employee].[Role]    Script Date: 8/20/2020 7:30:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Employee].[Role](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](30) NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Employee].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Role] FOREIGN KEY([RoleID])
REFERENCES [Employee].[Role] ([ID])
GO
ALTER TABLE [Employee].[Employee] CHECK CONSTRAINT [FK_Employee_Role]
GO
USE [master]
GO
ALTER DATABASE [StockBridge] SET  READ_WRITE 
GO
